#!/bin/sh
# preinst script for quanergy-client-dev
#
# see: dh_installdeb(1)

set -e

# source debconf library
. /usr/share/debconf/confmodule

# Source dbconfig-common functions
if [ -f /usr/local/lib/libquanergy_client.so ]; then
  rm /usr/local/lib/libquanergy_client.so
fi
