#!/bin/sh
# postrm script for quanergy-client-dev
#
# see: dh_installdeb(1)

set -e

# source debconf library
. /usr/share/debconf/confmodule

# Source dbconfig-common functions
if [ -f /usr/local/lib/libquanergy_client.so.3.2.0 ]; then
  ln -sf /usr/local/lib/libquanergy_client.so.3.2.0 /usr/local/lib/libquanergy_client.so
fi
